spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.143/viewpoint?characterEncoding=utf-8&useSSL=false
    # HikariCP数据库连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
      #date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
    #add-mappings: false
  #mvc:
    #throw-exception-if-no-handler-found: true
server:
  port: 8090
weixin:
  mpAppId: wxdb4be0a5df7ee493
  mpAppSecret: 2db1413f3c3674025e1dfb12a8ff8962
projectUrl:
  wechatMpAuthorize: http://www.cswm.net.cn

